### ISSUE TITLE
add templates subfolders

### ISSUE THREAD

**Issue by bnomei** [floriankarsten/kirby3-parcel-build-kit#1]
for emails
https://getkirby.com/docs/guide/emails#html-plain-text

or when ppl use template components like blade, handlebars that support subfolders in template dir

**Comment by iskrisis** [comment]
Do you mean this? 
https://github.com/floriankarsten/kirby3-parcel-build-kit/commit/1405dce892e6c418d55e510a7ee8fa3f03f8346b
Hope i understood correctly
